
default: &default
  adapter: postgresql
  host: localhost
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: invoice
  username: sykhira
  password: root

test:
  <<: *default
  database: invoice
  username: sykhira
  password: root

production:
  url: <%= ENV['DATABASE_URL'] %>
